[phases.setup]
nixPkgs = ["python39", "chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r cloud_requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 app:app"